language: elixir
elixir:
  - 1.6
otp_release:
  - 20.1
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
script:
  - MIX_ENV=dev mix check_consistency
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
  - mix docs
