language: elixir
sudo: false
env:
  - MIX_ENV=test
elixir:
  - 1.6
otp_release:
  - 20.0
cache:
  directories:
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
    - stage: credo
      env:
        - MIX_ENV=dev
      script: mix credo --strict
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
    - stage: test
      env:
        - MIX_ENV=test
      before_script: mix deps.get
      script:
        - mix test --cover
        - mix coveralls.travis
    - stage: docs
      env:
        - MIX_ENV=dev
      script:
        - mix inch --depth 2
        - mix inch.report
